### ISSUE TITLE
tidb-lightning cannot rightly warn low nofile limit

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/br#930]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Import a tpcc 1400 warehouses parquet data from s3, with default ulimit.

2. What did you expect to see?
Lightning warning about the low nofile limit would crash the import procedure.

3. What did you see instead?
Nothing about it was mentioned until lightning fail due to exceed the open file limit.

4. What version of BR and TiDB/TiKV/PD are you using?

Cluster: v5.0.0-nightly (built in 2021-3-17)

5. Operation logs  
Because this log contains some internal information, see it at [google drive](https://drive.google.com/file/d/1O81I4zpuNb6__vQNdw1tM_FSgCMKYTTr/view?usp=sharing).

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
```toml
[lightning]
# 日志
level = "debug"
file = "tidb-lightning#3.log"
pprof-port = 8289

[tikv-importer]
# 选择使用的 local 后端
backend = "local"
# 设置排序的键值对的临时存放地址，目标路径需要是一个空目录
"sorted-kv-dir" = "/lightning-data/sorted-kv-dir"

[mydumper]
# 源数据目录。
data-source-dir = "s3://tools-uw2/tpcc/100g-tpcc1400-parquet?region=us-west-2"

filter = ['*.*', '!mysql.*', '!sys.*', '!INFORMATION_SCHEMA.*', '!PERFORMANCE_SCHEMA.*', '!METRICS_SCHEMA.*', '!INSPECTION_SCHEMA.*']

[tidb]
# 目标集群的信息
host = "redacted"
port = 4000
user = "root"
password = "redacted"
# 表架构信息在从 TiDB 的“状态端口”获取。
status-port = 10080
# 集群 pd 的地址
pd-addr = "redacted:2379"
```
